# Generated by Django 6.1 on 2026-08-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('founder', 'Founder'), ('investor', 'Investor'), ('admin', 'Admin')], max_length=20),
        ),
    ]
