# Generated by Django 6.1 on 2026-10-09 13:43

from django.db import migrations, models


def blank_out_null_bios(apps, schema_editor):
    """bio becomes NOT NULL below; existing rows hold NULL and would break it."""
    User = apps.get_model("accounts", "User")
    User.objects.filter(bio__isnull=True).update(bio="")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.RunPython(
            blank_out_null_bios, migrations.RunPython.noop, elidable=True
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
    ]
