# Generated by Django 6.1 on 2026-08-27 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea', models.TextField()),
                ('industry', models.CharField(max_length=150)),
                ('problem', models.TextField()),
                ('solution', models.TextField()),
                ('target_customer', models.TextField()),
                ('differentiator', models.TextField()),
                ('country', models.CharField(max_length=100)),
                ('business_model', models.CharField(choices=[('subscription', 'Subscription'), ('commission', 'Commission'), ('one_time', 'One-time purchase'), ('freemium', 'Freemium'), ('advertising', 'Advertising'), ('other', 'Other')], max_length=20)),
                ('stage', models.CharField(choices=[('idea', 'Just an idea'), ('prototype', 'Prototype'), ('mvp', 'MVP'), ('launched', 'Launched'), ('revenue', 'Generating revenue')], max_length=20)),
                ('funding_requirement', models.DecimalField(decimal_places=2, max_digits=14)),
                ('competitors', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('published', 'Published'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IdeaReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executive_summary', models.TextField(blank=True)),
                ('problem_validation', models.TextField(blank=True)),
                ('solution_evaluation', models.TextField(blank=True)),
                ('target_customer_analysis', models.TextField(blank=True)),
                ('tam', models.TextField(blank=True)),
                ('sam', models.TextField(blank=True)),
                ('som', models.TextField(blank=True)),
                ('competitor_analysis', models.TextField(blank=True)),
                ('competitive_advantage', models.TextField(blank=True)),
                ('business_model_analysis', models.TextField(blank=True)),
                ('revenue_potential', models.TextField(blank=True)),
                ('market_trends', models.TextField(blank=True)),
                ('risk_analysis', models.TextField(blank=True)),
                ('funding_recommendation', models.TextField(blank=True)),
                ('customer_segments', models.TextField(blank=True)),
                ('go_to_market_strategy', models.TextField(blank=True)),
                ('ai_validation_score', models.FloatField(blank=True, null=True)),
                ('recommendations', models.TextField(blank=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='ideas.idea')),
            ],
        ),
    ]
