# Generated by Django 6.1 on 2026-10-09 13:50

from django.conf import settings
from django.db import migrations, models
from django.db.models import F


def backfill_published_at(apps, schema_editor):
    """Ideas published before this field existed have no timestamp; the closest
    honest value is when they were created."""
    Idea = apps.get_model("ideas", "Idea")
    Idea.objects.filter(status="published", published_at__isnull=True).update(
        published_at=F("created_at")
    )


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_idea_title_ideaview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('draft', 'Draft'), ('published', 'Published'), ('failed', 'Failed')], default='processing', max_length=20),
        ),
        migrations.RunPython(
            backfill_published_at, migrations.RunPython.noop, elidable=True
        ),
        migrations.AddIndex(
            model_name='idea',
            index=models.Index(fields=['status', '-created_at'], name='ideas_idea_status_57b413_idx'),
        ),
    ]
