# Generated by Django 6.1 on 2026-10-09 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connectionrequest',
            options={'ordering': ['-requested_at']},
        ),
    ]
